import {
  Blocks,
  MapPin,
  Bot,
  LayoutDashboard,
  Plug,
  MonitorSmartphone,
  Search,
  PenTool,
  Code2,
  Rocket,
  Target,
  Gauge,
  Handshake,
  Sparkles,
  Braces,
  Mail,
  Phone,
  MessageCircle,
  Briefcase,
  RefreshCw,
  CheckCircle2,
  Activity,
  Clock,
  ShoppingBag,
  FileText,
  Database,
  Server,
} from "lucide-react";

// Atom: Icon — renders a named icon from the Lucide icon library.
const MAP = {
  blocks: Blocks,
  map: MapPin,
  ai: Bot,
  dashboard: LayoutDashboard,
  plug: Plug,
  responsive: MonitorSmartphone,
  search: Search,
  pen: PenTool,
  code: Code2,
  rocket: Rocket,
  target: Target,
  gauge: Gauge,
  handshake: Handshake,
  sparkles: Sparkles,
  braces: Braces,
  mail: Mail,
  phone: Phone,
  chat: MessageCircle,
  briefcase: Briefcase,
  refresh: RefreshCw,
  check: CheckCircle2,
  activity: Activity,
  clock: Clock,
  shopify: ShoppingBag,
  cms: FileText,
  database: Database,
  server: Server,
};

export default function Icon({ name, size = 26, strokeWidth = 1.9, ...rest }) {
  const Cmp = MAP[name] || Sparkles;
  return <Cmp size={size} strokeWidth={strokeWidth} {...rest} />;
}
